"""Add user model

Revision ID: 1a0af2525f85
Revises: c0675d487cb2
Create Date: 2025-09-15 11:43:44.347810

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1a0af2525f85'
down_revision: Union[str, Sequence[str], None] = 'c0675d487cb2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cart_items', sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False))
    op.drop_column('cart_items', 'os_active')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cart_items', sa.Column('os_active', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=False))
    op.drop_column('cart_items', 'is_active')
    # ### end Alembic commands ###
