"""Add user model

Revision ID: 38ce22d4c0ec
Revises: 6d0086fd4208
Create Date: 2025-09-16 22:42:25.331703

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '38ce22d4c0ec'
down_revision: Union[str, Sequence[str], None] = '6d0086fd4208'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('wishlist_items', sa.Column('wishlist_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'wishlist_items', 'wishlist', ['wishlist_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'wishlist_items', type_='foreignkey')
    op.drop_column('wishlist_items', 'wishlist_id')
    # ### end Alembic commands ###
