"""Add user model

Revision ID: c0675d487cb2
Revises: 5b6797b70db9
Create Date: 2025-09-15 11:36:05.119533

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c0675d487cb2'
down_revision: Union[str, Sequence[str], None] = '5b6797b70db9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    from sqlalchemy import text

    op.add_column(
    'cart_items',
    sa.Column('is_active', sa.Boolean(), nullable=False, server_default=text('true'))
)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cart_items', 'os_active')
    # ### end Alembic commands ###
