"""Update orders model

Revision ID: c1c530ac8e1d
Revises: 7079087db62d
Create Date: 2025-09-23 22:13:33.397482

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c1c530ac8e1d'
down_revision: Union[str, Sequence[str], None] = '7079087db62d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('_total_price', sa.Float(), nullable=False, server_default='0.0'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', '_total_price')
    # ### end Alembic commands ###
